baseURL = "https://flwdl.github.io/"
languageCode = "zh-Hans"
title = "FLWDL"

[params]
  titleLanguage = "en"
  han = true
  displayLogo = true
  logoURL = "/images/site-logo.png"
  mathJaX = true

[menu]
  [[menu.main]]
    url = "/subscribe"
    name = "订阅"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
