baseURL = "https://flwdl.github.io/"
copyright = "除特别说明外，本站所有内容均采用知识共享署名-相同方式共享 4.0 国际许可协议进行许可"
languageCode = "zh-Hans"
newContentEditor = "code"
title = "FLWDL"
theme = "flwdl"

[author]
  name = "FLWDL"
  email = "flwdl@foxmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    url = "/subscribe"
    name = "订阅"
    weight = 10
  [[menu.main]]
    url = "/guestbook"
    name = "留言"
    weight = 1
  [[menu.main]]
    url="/about"
    name = "关于"
    weight = 5

[params]
  titleLanguage = "en"
  description = "FLWDL 的网站"
  displayLogo = true
  logoURL = "/images/site-logo.svg"
  mobileMenu = true    # 小屏幕上将菜单栏折叠
  commentRepo = "flwdl/website-comments"
