baseURL = "https://flwdl.github.io/"
copyright = "除特别说明外，本站所有内容均采用知识共享署名-相同方式共享 4.0 国际许可协议进行许可"
languageCode = "zh-Hans"
newContentEditor = "code"
title = "FLWDL"

[author]
  name = "FLWDL"
  email = "flwdl@foxmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    url = "/subscribe"
    name = "订阅"
    weight = 1

[params]
  titleLanguage = "en"
  description = "FLWDL 的网站"
  displayLogo = true
  logoURL = "/images/site-logo.png"
  mathJaX = true
  mobileMenu = false    # 小屏幕上将菜单栏折叠