baseURL = "https://flwdl.github.io/"
languageCode = "zh-Hans"
title = "FLWDL"

[params]
  titleLanguage = "en"
  han = true
  displayLogo = true
  logoURL = "/images/site-logo.png"
  mathJaX = true

[menu]
  [[menu.main]]
    url = "/"
    name = "home"
    weight = 1
  [[menu.main]]
    url = "/posts"
    name = "posts"
    weight = 11

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
